import {
    POWER_DEFS,
    getPowerMapForClass,
    PowerDefinition,
    PowerElement,
    ChampionType,
} from './PowerDefinitions';
import { makeFusionDef, fusionId } from './FusionFactory';

const CLASSES: ChampionType[] = ['barbarian', 'ranger', 'mage'];

/** All 10 element-pair fusions per class, generated by composing base defs. */
export const FUSION_DEFS: Record<string, PowerDefinition> = (() => {
    const out: Record<string, PowerDefinition> = {};
    for (const c of CLASSES) {
        const map = getPowerMapForClass(c);
        const elems = Object.keys(map) as PowerElement[];
        for (let i = 0; i < elems.length; i++) {
            for (let j = i + 1; j < elems.length; j++) {
                const a = POWER_DEFS[map[elems[i]]];
                const b = POWER_DEFS[map[elems[j]]];
                const def = makeFusionDef(a, b);
                out[def.id] = def;
            }
        }
    }
    return out;
})();

/**
 * Ultimate defs, aggregated from per-class modules. Populated in Task 4.
 * Kept as a mutable record so per-class ultimate modules register into it.
 */
export const ULTIMATE_DEFS: Record<string, PowerDefinition> = {};

/** Resolve any power def id across all three tiers. */
export function getAnyPowerDef(id: string): PowerDefinition | undefined {
    return POWER_DEFS[id] ?? FUSION_DEFS[id] ?? ULTIMATE_DEFS[id];
}

/** The tier-2 fusion produced by two BASE power ids of the same class, or null. */
export function getFusionFor(idA: string, idB: string): PowerDefinition | null {
    const a = POWER_DEFS[idA];
    const b = POWER_DEFS[idB];
    if (!a || !b) return null;
    const classA = idA.split('_')[0] as ChampionType;
    const classB = idB.split('_')[0] as ChampionType;
    if (classA !== classB) return null;
    return FUSION_DEFS[fusionId(classA, a.element, b.element)] ?? null;
}

/** The hand-authored ultimates available to a class. */
export function getUltimatesForClass(type: ChampionType): PowerDefinition[] {
    return Object.values(ULTIMATE_DEFS).filter(d => d.championType === type);
}
