import { ItemDef, SetDef } from './ItemTypes';

export const ITEM_SETS: SetDef[] = [
    {
        id: 'berserkers_wrath', name: "Berserker's Wrath", kind: 'classic',
        pieces: ['gorefang', 'skullcage_of_rage', 'bloodforged_plate'],
        tiers: [
            { pieces: 2, bonus: { attackSpeedPct: 20 }, text: '+20% attack speed' },
            { pieces: 3, effect: 'rage', text: 'RAGE: below 50% HP, +60% basic damage and a furious red glow' },
        ],
    },
    {
        id: 'windrunner', name: 'Windrunner', kind: 'classic',
        pieces: ['stormpiercer', 'galeskimmers', 'feather_of_the_zephyr'],
        tiers: [
            { pieces: 2, bonus: { moveSpeedPct: 15 }, text: '+15% move speed' },
            { pieces: 3, effect: 'ricochet', text: 'RICOCHET: arrows bounce to a nearby enemy at 60% damage' },
        ],
    },
    {
        id: 'archmages_echo', name: "Archmage's Echo", kind: 'classic',
        pieces: ['staff_of_echoes', 'mindcrown', 'runeweave_leggings'],
        tiers: [
            { pieces: 2, bonus: { cooldownPct: 10 }, text: '−10% power cooldowns' },
            { pieces: 3, effect: 'echo', text: 'ECHO: power casts have a 25% chance to instantly recast free' },
        ],
    },
    {
        id: 'goblin_fortune', name: 'Goblin Fortune', kind: 'classic',
        pieces: ['gribbles_lucky_coin', 'penny_pincher_loafers', 'greedhelm'],
        tiers: [
            { pieces: 2, bonus: { goldGainPct: 25 }, text: '+25% gold from kills' },
            { pieces: 3, effect: 'midas', text: 'MIDAS: 15% chance kills pay double; every 150g earned bursts a coin nova' },
        ],
    },
];

export const ITEM_CATALOG: ItemDef[] = [
    // ── Berserker's Wrath (barbarian) ────────────────────────────────────────
    { id: 'gorefang', name: 'Gorefang', slot: 'weapon', rarity: 'rare',
      classes: ['barbarian'], setId: 'berserkers_wrath', glyph: '🪓',
      mods: { basicDamagePct: 20 },
      flavor: 'Still hungry. Always hungry.' },
    { id: 'skullcage_of_rage', name: 'Skullcage of Rage', slot: 'helmet', rarity: 'rare',
      classes: ['barbarian'], setId: 'berserkers_wrath', glyph: '💀',
      mods: { attackSpeedPct: 10, maxHealth: 10 },
      flavor: 'The previous owner is still angry about it.' },
    { id: 'bloodforged_plate', name: 'Bloodforged Plate', slot: 'chest', rarity: 'epic',
      classes: ['barbarian'], setId: 'berserkers_wrath', glyph: '🛡',
      mods: { damageTakenPct: 12, maxHealth: 30 },
      flavor: 'Forged in blood. Washed never.' },

    // ── Windrunner (ranger) ──────────────────────────────────────────────────
    { id: 'stormpiercer', name: 'Stormpiercer', slot: 'weapon', rarity: 'rare',
      classes: ['ranger'], setId: 'windrunner', glyph: '🏹',
      mods: { basicDamagePct: 15, attackSpeedPct: 10 },
      flavor: 'The wind files a complaint every time you draw it.' },
    { id: 'galeskimmers', name: 'Galeskimmers', slot: 'boots', rarity: 'rare',
      classes: ['ranger'], setId: 'windrunner', glyph: '👢',
      mods: { moveSpeedPct: 12 },
      flavor: 'Technically the boots are jogging. You just live in them.' },
    { id: 'feather_of_the_zephyr', name: 'Feather of the Zephyr', slot: 'trinket', rarity: 'epic',
      classes: ['ranger'], setId: 'windrunner', glyph: '🪶',
      mods: { moveSpeedPct: 8, critChance: 0.08 },
      flavor: 'Plucked from a very fast, very annoyed bird.' },

    // ── Archmage's Echo (mage) ───────────────────────────────────────────────
    { id: 'staff_of_echoes', name: 'Staff of Echoes', slot: 'weapon', rarity: 'rare',
      classes: ['mage'], setId: 'archmages_echo', glyph: '🪄',
      mods: { powerDamagePct: 20 },
      flavor: 'Echoes… echoes… echoes…' },
    { id: 'mindcrown', name: 'Mindcrown', slot: 'helmet', rarity: 'rare',
      classes: ['mage'], setId: 'archmages_echo', glyph: '🌀',
      mods: { cooldownPct: 8 },
      flavor: 'Thinks two thoughts at once. Both are about fireballs.' },
    { id: 'runeweave_leggings', name: 'Runeweave Leggings', slot: 'legs', rarity: 'epic',
      classes: ['mage'], setId: 'archmages_echo', glyph: '✨',
      mods: { powerDamagePct: 15, moveSpeedPct: 6 },
      flavor: 'Every rune is a typo that turned out fine.' },

    // ── Goblin Fortune (all classes) ─────────────────────────────────────────
    { id: 'gribbles_lucky_coin', name: "Gribble's Lucky Coin", slot: 'trinket', rarity: 'rare',
      classes: 'all', setId: 'goblin_fortune', glyph: '🪙',
      mods: { goldGainPct: 10, critChance: 0.05 },
      flavor: '"Found it in YOUR pocket, actually." — Gribble' },
    { id: 'penny_pincher_loafers', name: 'Penny-Pincher Loafers', slot: 'boots', rarity: 'common',
      classes: 'all', setId: 'goblin_fortune', glyph: '🥿',
      mods: { moveSpeedPct: 8, goldGainPct: 5 },
      flavor: 'Squeak with joy near unattended coin.' },
    { id: 'greedhelm', name: 'Greedhelm', slot: 'helmet', rarity: 'rare',
      classes: 'all', setId: 'goblin_fortune', glyph: '⛑',
      mods: { goldGainPct: 10, maxHealth: 10 },
      flavor: 'The visor doubles as a coin slot.' },

    // ── Standalone weapons ───────────────────────────────────────────────────
    { id: 'butchers_cleaver', name: "Butcher's Cleaver", slot: 'weapon', rarity: 'common',
      classes: ['barbarian'], glyph: '🔪',
      mods: { basicDamagePct: 12 },
      flavor: 'Health code violation in 12 kingdoms.' },
    { id: 'worldsplitter', name: 'Worldsplitter', slot: 'weapon', rarity: 'legendary',
      classes: ['barbarian'], glyph: '⚒',
      mods: { basicDamagePct: 30 }, effectId: 'shockwave',
      flavor: 'The ground has learned to flinch.' },
    { id: 'oakshot_bow', name: 'Oakshot Bow', slot: 'weapon', rarity: 'common',
      classes: ['ranger'], glyph: '🪵',
      mods: { basicDamagePct: 12 },
      flavor: 'Made from a tree that owed someone money.' },
    { id: 'comet_driver', name: 'Comet Driver', slot: 'weapon', rarity: 'legendary',
      classes: ['ranger'], glyph: '☄',
      mods: { critChance: 0.15 }, effectId: 'critExplode',
      flavor: 'Aim at the goblin. Hit the postcode.' },
    { id: 'apprentice_focus', name: 'Apprentice Focus', slot: 'weapon', rarity: 'common',
      classes: ['mage'], glyph: '🔮',
      mods: { powerDamagePct: 12 },
      flavor: 'Slightly singed. Mostly enthusiastic.' },
    { id: 'emberwand', name: 'Emberwand', slot: 'weapon', rarity: 'epic',
      classes: ['mage'], glyph: '🔥',
      mods: { powerDamagePct: 15 }, effectId: 'burnOnHit',
      flavor: 'Warranty void if pointed at anything flammable. So: void.' },

    // ── Standalone armor & trinkets (all classes) ────────────────────────────
    { id: 'ironbrow_visor', name: 'Ironbrow Visor', slot: 'helmet', rarity: 'common',
      classes: 'all', glyph: '🪖',
      mods: { damageTakenPct: 8 },
      flavor: 'Blocks blows AND unsolicited advice.' },
    { id: 'crown_of_focus', name: 'Crown of Focus', slot: 'helmet', rarity: 'epic',
      classes: 'all', glyph: '👑',
      mods: { powerDamagePct: 15, critChance: 0.08 },
      flavor: 'Concentrate. Conquer. Repeat.' },
    { id: 'padded_jerkin', name: 'Padded Jerkin', slot: 'chest', rarity: 'common',
      classes: 'all', glyph: '🦺',
      mods: { maxHealth: 25 },
      flavor: 'The padding is 90% optimism.' },
    { id: 'troll_hide_vest', name: 'Troll-Hide Vest', slot: 'chest', rarity: 'rare',
      classes: 'all', glyph: '🧥',
      mods: { maxHealth: 20, hpRegenPctPerSec: 0.005 },
      flavor: 'The troll wants it back. Walk faster.' },
    { id: 'thornmail_hauberk', name: 'Thornmail Hauberk', slot: 'chest', rarity: 'epic',
      classes: 'all', glyph: '🌵',
      mods: { damageTakenPct: 10 }, effectId: 'thorns',
      flavor: 'Hugs are now a tactical decision.' },
    { id: 'marchers_greaves', name: "Marchers' Greaves", slot: 'legs', rarity: 'common',
      classes: 'all', glyph: '🦵',
      mods: { moveSpeedPct: 8 },
      flavor: 'Left. Left. Left-right-left.' },
    { id: 'juggernaut_legplates', name: 'Juggernaut Legplates', slot: 'legs', rarity: 'epic',
      classes: 'all', glyph: '🦿',
      mods: { damageTakenPct: 15, knockback: 1 },
      flavor: 'You don\'t dodge. You happen to people.' },
    { id: 'sprintweave_boots', name: 'Sprintweave Boots', slot: 'boots', rarity: 'common',
      classes: 'all', glyph: '👟',
      mods: { moveSpeedPct: 10 },
      flavor: 'Woven from pure "gotta go".' },
    { id: 'comet_treads', name: 'Comet Treads', slot: 'boots', rarity: 'epic',
      classes: 'all', glyph: '💫',
      mods: { moveSpeedPct: 12, attackSpeedPct: 10 },
      flavor: 'Leave little sparkles. Insurance doesn\'t cover them.' },
    { id: 'bloodvial', name: 'Bloodvial', slot: 'trinket', rarity: 'rare',
      classes: 'all', glyph: '🧪',
      mods: { lifesteal: 0.06 },
      flavor: 'Do not shake. Do not ask whose.' },
    { id: 'chrono_charm', name: 'Chrono Charm', slot: 'trinket', rarity: 'epic',
      classes: 'all', glyph: '⏳',
      mods: {}, effectId: 'chrono',
      flavor: 'Ticks backwards when you\'re in trouble. So: constantly.' },
    { id: 'executioners_sigil', name: "Executioner's Sigil", slot: 'trinket', rarity: 'legendary',
      classes: 'all', glyph: '⚔',
      mods: { critChance: 0.15, critDamage: 0.35 },
      flavor: 'Pre-signed. Just add a name.' },
];

const _byId = new Map(ITEM_CATALOG.map(i => [i.id, i]));
const _setById = new Map(ITEM_SETS.map(s => [s.id, s]));

export function itemById(id: string): ItemDef | undefined { return _byId.get(id); }
export function setById(id: string): SetDef | undefined { return _setById.get(id); }
