/**
 * Item-icon bake server.
 *
 * Source GLBs live in `art-source/items/<id>/` and are deliberately OUTSIDE
 * `assets/` — webpack copies `assets/` wholesale into `dist/`, and shipping
 * ~5 MB of mesh per item would blow the Cloudflare per-asset budget. The
 * deployable artefact is the baked 256px WebP under `assets/items/icons/`.
 *
 * Flow: `node tools/item-icons/serve.mjs` → open the printed URL → the page
 * renders every GLB through one fixed camera/light rig and POSTs each result
 * back here → the server writes the WebPs and regenerates the TS manifest.
 */
import { createServer } from 'node:http';
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { extname, join, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '../..');
const SRC_DIR = join(ROOT, 'art-source/items');
const OUT_DIR = join(ROOT, 'assets/items/icons');
const MANIFEST_TS = join(ROOT, 'src/ui/generated/itemArt.ts');
const FRAMING = join(import.meta.dirname, 'framing.json');
const PORT = 9310;

const MIME = {
    '.html': 'text/html', '.js': 'text/javascript', '.mjs': 'text/javascript',
    '.json': 'application/json', '.glb': 'model/gltf-binary', '.css': 'text/css',
};

/** Locate the GLB each item directory holds (Tripo names outputs by task id). */
async function collectSources() {
    if (!existsSync(SRC_DIR)) return [];
    const framing = existsSync(FRAMING) ? JSON.parse(await readFile(FRAMING, 'utf8')) : {};
    const out = [];
    for (const id of (await readdir(SRC_DIR, { withFileTypes: true })).filter(d => d.isDirectory())) {
        const files = await readdir(join(SRC_DIR, id.name));
        const glb = files.find(f => f.endsWith('.glb'));
        if (!glb) continue;
        out.push({
            id: id.name,
            glb: `/glb/${id.name}/${glb}`,
            baked: existsSync(join(OUT_DIR, `${id.name}.webp`)),
            ...(framing[id.name] ?? {}),
        });
    }
    return out.sort((a, b) => a.id.localeCompare(b.id));
}

/** Regenerate the TS lookup the UI imports, from whatever is baked on disk. */
async function writeManifestTs() {
    const files = existsSync(OUT_DIR)
        ? (await readdir(OUT_DIR)).filter(f => f.endsWith('.webp')).sort()
        : [];
    const entries = files.map(f => `    '${f.replace(/\.webp$/, '')}': '${'assets/items/icons/' + f}',`);
    const body = `/** GENERATED by tools/item-icons/serve.mjs — do not edit by hand.
 *  Item id → baked icon URL. Absent ids fall back to the authored SVG glyph. */
export const ITEM_ART: Readonly<Record<string, string>> = {
${entries.join('\n')}
};
`;
    await mkdir(join(ROOT, 'src/ui/generated'), { recursive: true });
    await writeFile(MANIFEST_TS, body);
    return files.length;
}

async function serveFile(res, path, fallbackType) {
    try {
        const buf = await readFile(path);
        res.writeHead(200, { 'Content-Type': MIME[extname(path)] ?? fallbackType ?? 'application/octet-stream' });
        res.end(buf);
    } catch {
        res.writeHead(404).end('not found');
    }
}

const server = createServer(async (req, res) => {
    const url = new URL(req.url, `http://localhost:${PORT}`);
    const path = decodeURIComponent(url.pathname);

    if (req.method === 'POST' && path.startsWith('/save/')) {
        const id = path.slice('/save/'.length);
        const chunks = [];
        for await (const c of req) chunks.push(c);
        await mkdir(OUT_DIR, { recursive: true });
        const buf = Buffer.concat(chunks);
        await writeFile(join(OUT_DIR, `${id}.webp`), buf);
        console.log(`  baked ${id}.webp  (${(buf.length / 1024).toFixed(1)} KB)`);
        res.writeHead(200).end('ok');
        return;
    }
    if (req.method === 'POST' && path === '/done') {
        const n = await writeManifestTs();
        console.log(`\nmanifest: src/ui/generated/itemArt.ts (${n} icons)`);
        res.writeHead(200).end('ok');
        setTimeout(() => server.close(() => process.exit(0)), 250);
        return;
    }
    if (path === '/manifest.json') {
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify(await collectSources()));
        return;
    }
    if (path.startsWith('/glb/')) return serveFile(res, join(SRC_DIR, path.slice('/glb/'.length)));
    if (path.startsWith('/vendor/three/')) {
        return serveFile(res, join(ROOT, 'node_modules/three', path.slice('/vendor/three/'.length)), 'text/javascript');
    }
    return serveFile(res, join(import.meta.dirname, path === '/' ? 'renderer.html' : path));
});

if (process.argv.includes('--manifest-only')) {
    console.log(`manifest: ${await writeManifestTs()} icons`);
} else {
    const sources = await collectSources();
    server.listen(PORT, () => {
        console.log(`item-icon bake: ${sources.length} source GLB(s)`);
        for (const s of sources) console.log(`  · ${s.id}`);
        console.log(`\nopen http://127.0.0.1:${PORT}/  — the page bakes and exits the server when finished.`);
    });
}
