/**
 * Medieval Tower Tree — Physical/Mechanical towers.
 * 30 towers across 8 tiers branching from a single Medieval Tower base.
 */

import { TowerDefinition } from './TowerDefinitions';
import { StatusEffect } from './Tower';

// Helper to create a simple stone tower visual at varying sizes/colors per tier
function medievalVisual(
    height: number, width: number, color: [number, number, number],
    components: TowerDefinition['visual']['components'] = [],
    particles?: TowerDefinition['visual']['particles'],
    animations?: TowerDefinition['visual']['animations']
): TowerDefinition['visual'] {
    return {
        baseShape: 'cylinder',
        baseDimensions: { width, height, tessellation: 8 },
        baseColor: color,
        components,
        particles,
        animations,
    };
}

const STONE: [number, number, number] = [0.72, 0.68, 0.62];
const DARK_STONE: [number, number, number] = [0.55, 0.50, 0.45];
const WOOD: [number, number, number] = [0.55, 0.38, 0.22];
const IRON: [number, number, number] = [0.40, 0.40, 0.42];
const GOLD: [number, number, number] = [0.85, 0.70, 0.25];
const DARK_IRON: [number, number, number] = [0.30, 0.30, 0.32];
const RED_BANNER: [number, number, number] = [0.80, 0.20, 0.15];
const BLUE_BANNER: [number, number, number] = [0.15, 0.30, 0.75];
const SIEGE_WOOD: [number, number, number] = [0.48, 0.35, 0.20];

export const MEDIEVAL_TOWER_DEFS: TowerDefinition[] = [
    // ===== TIER 1 =====
    {
        id: 'medievalTower',
        name: 'Medieval Tower',
        description: 'A basic stone watchtower. The foundation of all medieval defenses.',
        tier: 1, tree: 'medieval', category: 'base',
        stats: { damage: 8, range: 5, fireRate: 1.0, cost: 50 },
        ability: { name: 'None', type: 'passive', cooldown: 0, effect: { kind: 'none' }, description: 'No special ability' },
        visual: medievalVisual(1.4, 1.2, STONE, [
            { shape: 'cylinder', dimensions: { diameter: 1.4, height: 0.2, tessellation: 8 }, color: DARK_STONE, position: [0, 0.8, 0] },
            { shape: 'cone', dimensions: { diameter: 1.5, height: 0.6, tessellation: 8 }, color: WOOD, position: [0, 1.2, 0] },
        ]),
        upgradePaths: ['archerTower', 'garrisonTower'],
        parentId: null,
        projectileColor: [0.8, 0.8, 0.8],
    },

    // ===== TIER 2 — DPS Branch =====
    {
        id: 'archerTower',
        name: 'Archer Tower',
        description: 'Skilled archers rain arrows on enemies with improved range.',
        tier: 2, tree: 'medieval', category: 'dps',
        stats: { damage: 12, range: 7, fireRate: 1.2, cost: 75 },
        ability: { name: 'Keen Eye', type: 'passive', cooldown: 0, effect: { kind: 'criticalHit', chance: 0.10, multiplier: 1.5 }, description: '10% chance for 1.5x critical hit' },
        visual: medievalVisual(1.8, 1.2, STONE, [
            { shape: 'cylinder', dimensions: { diameter: 1.4, height: 0.15, tessellation: 8 }, color: DARK_STONE, position: [0, 1.0, 0] },
            { shape: 'cone', dimensions: { diameter: 1.6, height: 0.7, tessellation: 8 }, color: [0.55, 0.30, 0.15], position: [0, 1.45, 0] },
            { shape: 'box', dimensions: { width: 0.08, height: 0.6, depth: 0.08 }, color: WOOD, position: [0.3, 1.5, 0] },
            { shape: 'box', dimensions: { width: 0.3, height: 0.04, depth: 0.15 }, color: RED_BANNER, position: [0.3, 1.85, 0] },
        ]),
        upgradePaths: ['longbowTower', 'repeaterTower'],
        parentId: 'medievalTower',
        projectileColor: [0.8, 0.7, 0.5],
    },

    // ===== TIER 2 — Tactical Branch =====
    {
        id: 'garrisonTower',
        name: 'Garrison Tower',
        description: 'A fortified garrison that provides tactical advantages.',
        tier: 2, tree: 'medieval', category: 'tactical',
        stats: { damage: 10, range: 5, fireRate: 0.8, cost: 75 },
        ability: { name: 'Rally', type: 'passive', cooldown: 0, effect: { kind: 'auraBuff', bonusDamage: 1, bonusFireRate: 0, bonusRange: 0, radius: 4 }, description: '+1 damage to nearby towers' },
        visual: medievalVisual(1.6, 1.5, STONE, [
            { shape: 'box', dimensions: { width: 1.6, height: 0.3, depth: 1.6 }, color: DARK_STONE, position: [0, 0.95, 0] },
            { shape: 'box', dimensions: { width: 0.3, height: 0.4, depth: 0.3 }, color: STONE, position: [0.55, 1.2, 0.55] },
            { shape: 'box', dimensions: { width: 0.3, height: 0.4, depth: 0.3 }, color: STONE, position: [-0.55, 1.2, -0.55] },
            { shape: 'box', dimensions: { width: 0.08, height: 0.7, depth: 0.08 }, color: WOOD, position: [0, 1.35, 0] },
            { shape: 'box', dimensions: { width: 0.35, height: 0.04, depth: 0.18 }, color: BLUE_BANNER, position: [0, 1.75, 0] },
        ]),
        upgradePaths: ['barracksTower', 'bulwarkTower'],
        parentId: 'medievalTower',
        projectileColor: [0.6, 0.6, 0.7],
    },

    // ===== TIER 3 — Precision =====
    {
        id: 'longbowTower',
        name: 'Longbow Tower',
        description: 'Expert longbowmen with devastating accuracy at extreme range.',
        tier: 3, tree: 'medieval', category: 'precision',
        stats: { damage: 18, range: 9, fireRate: 1.0, cost: 100 },
        ability: { name: 'Piercing Arrow', type: 'passive', cooldown: 0, effect: { kind: 'piercingShot', cooldown: 4, maxTargets: 3 }, description: 'Every 4s, arrow pierces up to 3 enemies' },
        visual: medievalVisual(2.2, 1.2, STONE, [
            { shape: 'cylinder', dimensions: { diameter: 1.0, height: 0.8, tessellation: 8 }, color: [0.68, 0.64, 0.58], position: [0, 1.5, 0] },
            { shape: 'cone', dimensions: { diameter: 1.3, height: 0.8, tessellation: 8 }, color: [0.50, 0.28, 0.14], position: [0, 2.3, 0] },
            { shape: 'box', dimensions: { width: 0.06, height: 0.8, depth: 0.06 }, color: WOOD, position: [0, 2.0, 0.35] },
        ]),
        upgradePaths: ['marksmanTower'],
        parentId: 'archerTower',
        projectileColor: [0.9, 0.8, 0.5],
    },

    // ===== TIER 3 — Rapid Fire =====
    {
        id: 'repeaterTower',
        name: 'Repeater Tower',
        description: 'Mechanical crossbows fire a storm of bolts at high speed.',
        tier: 3, tree: 'medieval', category: 'rapidfire',
        stats: { damage: 8, range: 6, fireRate: 2.5, cost: 100 },
        ability: { name: 'Spin Up', type: 'passive', cooldown: 0, effect: { kind: 'spinUp', maxBonus: 0.5, perSecond: 0.1 }, description: 'Fire rate increases while attacking the same area' },
        visual: medievalVisual(1.6, 1.4, STONE, [
            { shape: 'box', dimensions: { width: 1.5, height: 0.2, depth: 1.5 }, color: DARK_STONE, position: [0, 0.9, 0] },
            { shape: 'cylinder', dimensions: { diameter: 0.2, height: 0.6, tessellation: 6 }, color: IRON, position: [0.3, 1.3, 0] },
            { shape: 'cylinder', dimensions: { diameter: 0.2, height: 0.6, tessellation: 6 }, color: IRON, position: [-0.3, 1.3, 0] },
            { shape: 'box', dimensions: { width: 0.4, height: 0.15, depth: 0.3 }, color: WOOD, position: [0, 1.1, 0.3] },
        ]),
        upgradePaths: ['scorpionTower'],
        parentId: 'archerTower',
        projectileColor: [0.7, 0.7, 0.5],
    },

    // ===== TIER 3 — Support =====
    {
        id: 'barracksTower',
        name: 'Barracks Tower',
        description: 'Houses soldiers that buff nearby towers with combat experience.',
        tier: 3, tree: 'medieval', category: 'support',
        stats: { damage: 10, range: 5, fireRate: 0.8, cost: 100 },
        ability: { name: 'War Cry', type: 'passive', cooldown: 0, effect: { kind: 'auraBuff', bonusDamage: 2, bonusFireRate: 0.1, bonusRange: 0, radius: 5 }, description: '+2 damage +0.1 fire rate to nearby towers' },
        visual: medievalVisual(1.8, 1.6, STONE, [
            { shape: 'box', dimensions: { width: 1.7, height: 0.4, depth: 1.7 }, color: DARK_STONE, position: [0, 1.0, 0] },
            { shape: 'box', dimensions: { width: 0.3, height: 0.5, depth: 0.3 }, color: STONE, position: [0.6, 1.35, 0.6] },
            { shape: 'box', dimensions: { width: 0.3, height: 0.5, depth: 0.3 }, color: STONE, position: [-0.6, 1.35, -0.6] },
            { shape: 'box', dimensions: { width: 0.3, height: 0.5, depth: 0.3 }, color: STONE, position: [0.6, 1.35, -0.6] },
            { shape: 'box', dimensions: { width: 0.3, height: 0.5, depth: 0.3 }, color: STONE, position: [-0.6, 1.35, 0.6] },
            { shape: 'box', dimensions: { width: 0.08, height: 0.8, depth: 0.08 }, color: WOOD, position: [0, 1.5, 0] },
            { shape: 'box', dimensions: { width: 0.4, height: 0.05, depth: 0.2 }, color: RED_BANNER, position: [0, 1.95, 0] },
        ]),
        upgradePaths: ['warHall'],
        parentId: 'garrisonTower',
        projectileColor: [0.7, 0.6, 0.5],
    },

    // ===== TIER 3 — Defense =====
    {
        id: 'bulwarkTower',
        name: 'Bulwark Tower',
        description: 'Heavily fortified tower with siege weapons.',
        tier: 3, tree: 'medieval', category: 'defense',
        stats: { damage: 25, range: 7, fireRate: 0.5, cost: 100 },
        ability: { name: 'Armor Break', type: 'passive', cooldown: 0, effect: { kind: 'armorShatter', reductionPerStack: 0.05, maxStacks: 5, duration: 4 }, description: 'Hits reduce enemy armor by 5% per stack (max 5)' },
        visual: medievalVisual(1.6, 1.8, DARK_STONE, [
            { shape: 'box', dimensions: { width: 2.0, height: 0.3, depth: 2.0 }, color: STONE, position: [0, 0.9, 0] },
            { shape: 'box', dimensions: { width: 0.4, height: 0.5, depth: 0.4 }, color: DARK_STONE, position: [0.7, 1.2, 0.7] },
            { shape: 'box', dimensions: { width: 0.4, height: 0.5, depth: 0.4 }, color: DARK_STONE, position: [-0.7, 1.2, -0.7] },
            { shape: 'box', dimensions: { width: 0.4, height: 0.5, depth: 0.4 }, color: DARK_STONE, position: [0.7, 1.2, -0.7] },
            { shape: 'box', dimensions: { width: 0.4, height: 0.5, depth: 0.4 }, color: DARK_STONE, position: [-0.7, 1.2, 0.7] },
            { shape: 'cylinder', dimensions: { diameter: 0.3, height: 0.5, tessellation: 6 }, color: IRON, position: [0, 1.3, 0.4] },
        ]),
        upgradePaths: ['rampartTower'],
        parentId: 'garrisonTower',
        projectileColor: [0.5, 0.5, 0.55],
    },

    // ===== TIER 4 — Marksman =====
    {
        id: 'marksmanTower',
        name: 'Marksman Tower',
        description: 'Elite marksmen deal devastating critical strikes from afar.',
        tier: 4, tree: 'medieval', category: 'precision',
        stats: { damage: 28, range: 11, fireRate: 1.0, cost: 150 },
        ability: { name: 'Deadly Aim', type: 'passive', cooldown: 0, effect: { kind: 'criticalHit', chance: 0.20, multiplier: 2.0 }, description: '20% chance for 2x critical hit' },
        visual: medievalVisual(2.6, 1.1, [0.75, 0.72, 0.65], [
            { shape: 'cylinder', dimensions: { diameter: 0.9, height: 1.0, tessellation: 8 }, color: [0.70, 0.67, 0.60], position: [0, 1.8, 0] },
            { shape: 'cone', dimensions: { diameter: 1.2, height: 1.0, tessellation: 8 }, color: [0.45, 0.28, 0.15], position: [0, 2.8, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.2, tessellation: 6 }, color: [0.85, 0.22, 0.22], position: [0, 2.5, 0.4], emissive: 0.4 },
        ]),
        upgradePaths: ['hawkeyeTower', 'volleyTower'],
        parentId: 'longbowTower',
        projectileColor: [0.9, 0.3, 0.2],
    },

    // ===== TIER 4 — Scorpion =====
    {
        id: 'scorpionTower',
        name: 'Scorpion Tower',
        description: 'Mechanical siege crossbow with devastating rapid-fire bolts.',
        tier: 4, tree: 'medieval', category: 'rapidfire',
        stats: { damage: 12, range: 7, fireRate: 3.0, cost: 150 },
        ability: { name: 'Bolt Storm', type: 'passive', cooldown: 0, effect: { kind: 'multishot', extraProjectiles: 1 }, description: 'Each shot fires 2 bolts' },
        visual: medievalVisual(1.8, 1.4, STONE, [
            { shape: 'box', dimensions: { width: 1.6, height: 0.3, depth: 1.6 }, color: IRON, position: [0, 1.0, 0] },
            { shape: 'cylinder', dimensions: { diameter: 0.25, height: 0.8, tessellation: 6 }, color: DARK_IRON, position: [0.3, 1.4, 0.2] },
            { shape: 'cylinder', dimensions: { diameter: 0.25, height: 0.8, tessellation: 6 }, color: DARK_IRON, position: [-0.3, 1.4, 0.2] },
            { shape: 'box', dimensions: { width: 0.6, height: 0.2, depth: 0.4 }, color: SIEGE_WOOD, position: [0, 1.2, 0] },
        ]),
        upgradePaths: ['gatlingTower', 'siegeBallistaTower'],
        parentId: 'repeaterTower',
        projectileColor: [0.6, 0.6, 0.6],
    },

    // ===== TIER 4 — War Hall =====
    {
        id: 'warHall',
        name: 'War Hall',
        description: 'Grand hall that inspires great feats in nearby towers.',
        tier: 4, tree: 'medieval', category: 'support',
        stats: { damage: 12, range: 5, fireRate: 0.9, cost: 150 },
        ability: { name: 'Battle Standard', type: 'passive', cooldown: 0, effect: { kind: 'auraBuff', bonusDamage: 4, bonusFireRate: 0.2, bonusRange: 1, radius: 6 }, description: '+4 damage, +0.2 fire rate, +1 range to nearby towers' },
        visual: medievalVisual(2.0, 1.7, STONE, [
            { shape: 'box', dimensions: { width: 1.8, height: 0.5, depth: 1.8 }, color: DARK_STONE, position: [0, 1.1, 0] },
            { shape: 'cone', dimensions: { diameter: 2.0, height: 1.0, tessellation: 4 }, color: [0.50, 0.28, 0.14], position: [0, 1.85, 0] },
            { shape: 'box', dimensions: { width: 0.1, height: 1.0, depth: 0.1 }, color: WOOD, position: [0, 2.0, 0] },
            { shape: 'box', dimensions: { width: 0.5, height: 0.06, depth: 0.25 }, color: GOLD, position: [0, 2.5, 0] },
        ]),
        upgradePaths: ['commanderTower', 'wardenTower'],
        parentId: 'barracksTower',
        projectileColor: [0.85, 0.70, 0.25],
    },

    // ===== TIER 4 — Rampart =====
    {
        id: 'rampartTower',
        name: 'Rampart Tower',
        description: 'Massive fortification with heavy siege weapons.',
        tier: 4, tree: 'medieval', category: 'defense',
        stats: { damage: 40, range: 8, fireRate: 0.4, cost: 150 },
        ability: { name: 'Siege Strike', type: 'passive', cooldown: 0, effect: { kind: 'siegeShot', bonusDamage: 15, splashRadius: 2.5 }, description: '+15 bonus damage with 2.5 radius splash' },
        visual: medievalVisual(2.0, 2.0, DARK_STONE, [
            { shape: 'box', dimensions: { width: 2.2, height: 0.4, depth: 2.2 }, color: STONE, position: [0, 1.1, 0] },
            { shape: 'box', dimensions: { width: 0.5, height: 0.6, depth: 0.5 }, color: DARK_STONE, position: [0.8, 1.5, 0.8] },
            { shape: 'box', dimensions: { width: 0.5, height: 0.6, depth: 0.5 }, color: DARK_STONE, position: [-0.8, 1.5, -0.8] },
            { shape: 'box', dimensions: { width: 0.8, height: 0.4, depth: 0.3 }, color: SIEGE_WOOD, position: [0, 1.5, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.3, tessellation: 6 }, color: IRON, position: [0, 1.8, 0] },
        ]),
        upgradePaths: ['catapultTower', 'saboteurTower'],
        parentId: 'bulwarkTower',
        projectileColor: [0.5, 0.4, 0.3],
    },

    // ===== TIER 5-8 — Precision Branch A: Hawkeye line =====
    {
        id: 'hawkeyeTower',
        name: 'Hawkeye Tower',
        description: 'Eagle-eyed snipers with extraordinary range and critical power.',
        tier: 5, tree: 'medieval', category: 'precision',
        stats: { damage: 40, range: 13, fireRate: 1.0, cost: 200 },
        ability: { name: 'Eagle Strike', type: 'passive', cooldown: 0, effect: { kind: 'criticalHit', chance: 0.25, multiplier: 2.5 }, description: '25% chance for 2.5x critical hit' },
        visual: medievalVisual(3.0, 1.0, [0.78, 0.75, 0.68], [
            { shape: 'cylinder', dimensions: { diameter: 0.8, height: 1.2, tessellation: 8 }, color: [0.72, 0.69, 0.62], position: [0, 2.1, 0] },
            { shape: 'cone', dimensions: { diameter: 1.1, height: 1.2, tessellation: 8 }, color: [0.42, 0.25, 0.12], position: [0, 3.3, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.25, tessellation: 6 }, color: [0.90, 0.20, 0.15], position: [0, 2.8, 0.35], emissive: 0.5 },
        ]),
        upgradePaths: ['eagleTower'],
        parentId: 'marksmanTower',
        projectileColor: [0.95, 0.25, 0.15],
    },
    {
        id: 'eagleTower',
        name: 'Eagle Tower',
        description: 'Legendary marksmen guided by eagle spirits.',
        tier: 6, tree: 'medieval', category: 'precision',
        stats: { damage: 55, range: 14, fireRate: 1.1, cost: 275 },
        ability: { name: 'Eagle Spirit', type: 'passive', cooldown: 0, effect: { kind: 'criticalHit', chance: 0.30, multiplier: 2.8 }, description: '30% chance for 2.8x critical hit' },
        visual: medievalVisual(3.4, 1.0, [0.80, 0.77, 0.70], [
            { shape: 'cylinder', dimensions: { diameter: 0.8, height: 1.4, tessellation: 8 }, color: [0.74, 0.71, 0.64], position: [0, 2.4, 0] },
            { shape: 'cone', dimensions: { diameter: 1.1, height: 1.3, tessellation: 8 }, color: [0.40, 0.23, 0.10], position: [0, 3.7, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.3, tessellation: 6 }, color: [0.95, 0.85, 0.15], position: [0, 3.2, 0], emissive: 0.6 },
        ]),
        upgradePaths: ['hawkLordTower'],
        parentId: 'hawkeyeTower',
        projectileColor: [0.95, 0.85, 0.15],
    },
    {
        id: 'hawkLordTower',
        name: 'Hawk Lord Tower',
        description: 'Master of ranged warfare, no enemy escapes its gaze.',
        tier: 7, tree: 'medieval', category: 'precision',
        stats: { damage: 75, range: 15, fireRate: 1.2, cost: 375 },
        ability: { name: 'Death Mark', type: 'passive', cooldown: 0, effect: { kind: 'criticalHit', chance: 0.35, multiplier: 3.0 }, description: '35% chance for 3x critical hit' },
        visual: medievalVisual(3.8, 1.0, [0.82, 0.79, 0.72], [
            { shape: 'cylinder', dimensions: { diameter: 0.8, height: 1.6, tessellation: 8 }, color: [0.76, 0.73, 0.66], position: [0, 2.7, 0] },
            { shape: 'cone', dimensions: { diameter: 1.2, height: 1.4, tessellation: 8 }, color: [0.38, 0.22, 0.10], position: [0, 4.1, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.35, tessellation: 6 }, color: [1.0, 0.90, 0.20], position: [0, 3.6, 0], emissive: 0.7 },
        ]),
        upgradePaths: ['zenithSpire'],
        parentId: 'eagleTower',
        projectileColor: [1.0, 0.90, 0.20],
    },
    {
        id: 'zenithSpire',
        name: 'Zenith Spire',
        description: 'The pinnacle of precision. Devastating single-target damage from extreme range.',
        tier: 8, tree: 'medieval', category: 'precision',
        stats: { damage: 100, range: 16, fireRate: 1.3, cost: 500 },
        ability: { name: 'Zenith Shot', type: 'passive', cooldown: 0, effect: { kind: 'criticalHit', chance: 0.40, multiplier: 3.5 }, description: '40% chance for 3.5x critical hit' },
        visual: medievalVisual(4.2, 1.0, [0.85, 0.82, 0.75], [
            { shape: 'cylinder', dimensions: { diameter: 0.7, height: 2.0, tessellation: 8 }, color: [0.78, 0.75, 0.68], position: [0, 3.1, 0] },
            { shape: 'cone', dimensions: { diameter: 1.0, height: 1.5, tessellation: 8 }, color: GOLD, position: [0, 4.8, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.4, tessellation: 8 }, color: [1.0, 0.95, 0.40], position: [0, 4.2, 0], emissive: 0.8 },
            { shape: 'torus', dimensions: { diameter: 1.2, thickness: 0.06, tessellation: 16 }, color: GOLD, position: [0, 3.5, 0], emissive: 0.3 },
        ],
        [{ type: 'ambient', emitRate: 5, color1: [1, 0.95, 0.4, 0.6], color2: [1, 0.85, 0.2, 0.3], minSize: 0.1, maxSize: 0.2, minLifeTime: 0.5, maxLifeTime: 1.0, offsetY: 4.0 }]),
        upgradePaths: [],
        parentId: 'hawkLordTower',
        projectileColor: [1.0, 0.95, 0.40],
    },

    // ===== TIER 5-8 — Precision Branch B: Volley line =====
    {
        id: 'volleyTower',
        name: 'Volley Tower',
        description: 'Rains arrows upon groups of enemies simultaneously.',
        tier: 5, tree: 'medieval', category: 'volley',
        stats: { damage: 20, range: 10, fireRate: 1.2, cost: 200 },
        ability: { name: 'Arrow Rain', type: 'passive', cooldown: 0, effect: { kind: 'multishot', extraProjectiles: 2 }, description: 'Each shot fires 3 arrows' },
        visual: medievalVisual(2.4, 1.3, STONE, [
            { shape: 'cylinder', dimensions: { diameter: 1.5, height: 0.2, tessellation: 8 }, color: DARK_STONE, position: [0, 1.3, 0] },
            { shape: 'cone', dimensions: { diameter: 1.6, height: 0.8, tessellation: 8 }, color: WOOD, position: [0, 1.8, 0] },
            { shape: 'box', dimensions: { width: 0.6, height: 0.1, depth: 0.4 }, color: IRON, position: [0, 1.4, 0] },
        ]),
        upgradePaths: ['stormOfArrowsTower'],
        parentId: 'marksmanTower',
        projectileColor: [0.8, 0.7, 0.5],
    },
    {
        id: 'stormOfArrowsTower',
        name: 'Storm of Arrows',
        description: 'A tempest of arrows that blankets the battlefield.',
        tier: 6, tree: 'medieval', category: 'volley',
        stats: { damage: 28, range: 11, fireRate: 1.4, cost: 275 },
        ability: { name: 'Arrow Storm', type: 'passive', cooldown: 0, effect: { kind: 'multishot', extraProjectiles: 3 }, description: 'Each shot fires 4 arrows' },
        visual: medievalVisual(2.8, 1.3, STONE, [
            { shape: 'cylinder', dimensions: { diameter: 1.5, height: 0.25, tessellation: 8 }, color: DARK_STONE, position: [0, 1.5, 0] },
            { shape: 'cone', dimensions: { diameter: 1.7, height: 0.9, tessellation: 8 }, color: WOOD, position: [0, 2.1, 0] },
            { shape: 'box', dimensions: { width: 0.8, height: 0.12, depth: 0.5 }, color: IRON, position: [0, 1.6, 0] },
        ]),
        upgradePaths: ['arrowHellTower'],
        parentId: 'volleyTower',
        projectileColor: [0.8, 0.7, 0.4],
    },
    {
        id: 'arrowHellTower',
        name: 'Arrow Hell',
        description: 'So many arrows they blot out the sun.',
        tier: 7, tree: 'medieval', category: 'volley',
        stats: { damage: 35, range: 12, fireRate: 1.6, cost: 375 },
        ability: { name: 'Arrow Hell', type: 'passive', cooldown: 0, effect: { kind: 'multishot', extraProjectiles: 4 }, description: 'Each shot fires 5 arrows' },
        visual: medievalVisual(3.2, 1.3, STONE, [
            { shape: 'cylinder', dimensions: { diameter: 1.6, height: 0.3, tessellation: 8 }, color: DARK_STONE, position: [0, 1.7, 0] },
            { shape: 'cone', dimensions: { diameter: 1.8, height: 1.0, tessellation: 8 }, color: [0.48, 0.28, 0.12], position: [0, 2.4, 0] },
            { shape: 'box', dimensions: { width: 1.0, height: 0.15, depth: 0.6 }, color: IRON, position: [0, 1.8, 0] },
        ]),
        upgradePaths: ['arrowMaelstrom'],
        parentId: 'stormOfArrowsTower',
        projectileColor: [0.7, 0.6, 0.3],
    },
    {
        id: 'arrowMaelstrom',
        name: 'Arrow Maelstrom',
        description: 'The ultimate volley tower. A ceaseless rain of arrows annihilates all.',
        tier: 8, tree: 'medieval', category: 'volley',
        stats: { damage: 45, range: 13, fireRate: 1.8, cost: 500 },
        ability: { name: 'Maelstrom', type: 'passive', cooldown: 0, effect: { kind: 'multishot', extraProjectiles: 5 }, description: 'Each shot fires 6 arrows at nearby enemies' },
        visual: medievalVisual(3.6, 1.4, STONE, [
            { shape: 'cylinder', dimensions: { diameter: 1.7, height: 0.35, tessellation: 8 }, color: DARK_STONE, position: [0, 1.9, 0] },
            { shape: 'cone', dimensions: { diameter: 2.0, height: 1.2, tessellation: 8 }, color: [0.45, 0.26, 0.10], position: [0, 2.8, 0] },
            { shape: 'box', dimensions: { width: 1.2, height: 0.18, depth: 0.7 }, color: IRON, position: [0, 2.0, 0] },
            { shape: 'torus', dimensions: { diameter: 1.6, thickness: 0.06, tessellation: 16 }, color: GOLD, position: [0, 2.0, 0], emissive: 0.3 },
        ],
        [{ type: 'ambient', emitRate: 8, color1: [0.8, 0.7, 0.4, 0.5], color2: [0.6, 0.5, 0.3, 0.3], minSize: 0.05, maxSize: 0.15, minLifeTime: 0.3, maxLifeTime: 0.8, offsetY: 2.5 }]),
        upgradePaths: [],
        parentId: 'arrowHellTower',
        projectileColor: [0.85, 0.75, 0.35],
    },

    // ===== TIER 5-8 — Rapid Fire Branch A: Gatling line =====
    {
        id: 'gatlingTower',
        name: 'Gatling Tower',
        description: 'Clockwork-driven rapid fire that shreds enemies.',
        tier: 5, tree: 'medieval', category: 'rapidfire',
        stats: { damage: 14, range: 7, fireRate: 3.5, cost: 200 },
        ability: { name: 'Overclock', type: 'passive', cooldown: 0, effect: { kind: 'spinUp', maxBonus: 1.0, perSecond: 0.15 }, description: 'Fire rate ramps up to +100% while shooting' },
        visual: medievalVisual(1.8, 1.5, IRON, [
            { shape: 'cylinder', dimensions: { diameter: 0.3, height: 1.0, tessellation: 6 }, color: DARK_IRON, position: [0.25, 1.4, 0.2] },
            { shape: 'cylinder', dimensions: { diameter: 0.3, height: 1.0, tessellation: 6 }, color: DARK_IRON, position: [-0.25, 1.4, 0.2] },
            { shape: 'cylinder', dimensions: { diameter: 0.3, height: 1.0, tessellation: 6 }, color: DARK_IRON, position: [0, 1.4, -0.2] },
            { shape: 'box', dimensions: { width: 0.8, height: 0.3, depth: 0.6 }, color: SIEGE_WOOD, position: [0, 1.1, 0] },
        ]),
        upgradePaths: ['repeaterBastion'],
        parentId: 'scorpionTower',
        projectileColor: [0.6, 0.6, 0.6],
    },
    {
        id: 'repeaterBastion',
        name: 'Repeater Bastion',
        description: 'Armored bastion with twin repeating crossbows.',
        tier: 6, tree: 'medieval', category: 'rapidfire',
        stats: { damage: 18, range: 7, fireRate: 4.0, cost: 275 },
        ability: { name: 'Twin Repeaters', type: 'passive', cooldown: 0, effect: { kind: 'spinUp', maxBonus: 1.2, perSecond: 0.18 }, description: 'Fire rate ramps up to +120% while shooting' },
        visual: medievalVisual(2.0, 1.6, IRON, [
            { shape: 'cylinder', dimensions: { diameter: 0.3, height: 1.2, tessellation: 6 }, color: DARK_IRON, position: [0.35, 1.5, 0.2] },
            { shape: 'cylinder', dimensions: { diameter: 0.3, height: 1.2, tessellation: 6 }, color: DARK_IRON, position: [-0.35, 1.5, 0.2] },
            { shape: 'box', dimensions: { width: 1.0, height: 0.35, depth: 0.7 }, color: SIEGE_WOOD, position: [0, 1.2, 0] },
            { shape: 'torus', dimensions: { diameter: 0.6, thickness: 0.05, tessellation: 12 }, color: GOLD, position: [0, 1.5, 0] },
        ]),
        upgradePaths: ['clockworkTower'],
        parentId: 'gatlingTower',
        projectileColor: [0.6, 0.6, 0.5],
    },
    {
        id: 'clockworkTower',
        name: 'Clockwork Tower',
        description: 'Dwarven clockwork mechanism fires at inhuman speed.',
        tier: 7, tree: 'medieval', category: 'rapidfire',
        stats: { damage: 22, range: 8, fireRate: 4.5, cost: 375 },
        ability: { name: 'Clockwork Fury', type: 'passive', cooldown: 0, effect: { kind: 'spinUp', maxBonus: 1.5, perSecond: 0.20 }, description: 'Fire rate ramps up to +150% while shooting' },
        visual: medievalVisual(2.2, 1.6, IRON, [
            { shape: 'cylinder', dimensions: { diameter: 0.25, height: 1.4, tessellation: 6 }, color: DARK_IRON, position: [0.35, 1.6, 0.2] },
            { shape: 'cylinder', dimensions: { diameter: 0.25, height: 1.4, tessellation: 6 }, color: DARK_IRON, position: [-0.35, 1.6, 0.2] },
            { shape: 'cylinder', dimensions: { diameter: 0.25, height: 1.4, tessellation: 6 }, color: DARK_IRON, position: [0, 1.6, -0.3] },
            { shape: 'box', dimensions: { width: 1.0, height: 0.4, depth: 0.8 }, color: SIEGE_WOOD, position: [0, 1.3, 0] },
            { shape: 'torus', dimensions: { diameter: 1.0, thickness: 0.08, tessellation: 16 }, color: GOLD, position: [0, 1.6, 0], emissive: 0.2 },
        ]),
        upgradePaths: ['perpetualEngine'],
        parentId: 'repeaterBastion',
        projectileColor: [0.7, 0.65, 0.4],
    },
    {
        id: 'perpetualEngine',
        name: 'Perpetual Engine',
        description: 'An unstoppable machine of war. Infinite firing speed potential.',
        tier: 8, tree: 'medieval', category: 'rapidfire',
        stats: { damage: 28, range: 8, fireRate: 5.0, cost: 500 },
        ability: { name: 'Perpetual Motion', type: 'passive', cooldown: 0, effect: { kind: 'spinUp', maxBonus: 2.0, perSecond: 0.25 }, description: 'Fire rate ramps up to +200% while shooting' },
        visual: medievalVisual(2.4, 1.7, IRON, [
            { shape: 'cylinder', dimensions: { diameter: 0.22, height: 1.6, tessellation: 6 }, color: DARK_IRON, position: [0.4, 1.7, 0.25] },
            { shape: 'cylinder', dimensions: { diameter: 0.22, height: 1.6, tessellation: 6 }, color: DARK_IRON, position: [-0.4, 1.7, 0.25] },
            { shape: 'cylinder', dimensions: { diameter: 0.22, height: 1.6, tessellation: 6 }, color: DARK_IRON, position: [0.2, 1.7, -0.35] },
            { shape: 'cylinder', dimensions: { diameter: 0.22, height: 1.6, tessellation: 6 }, color: DARK_IRON, position: [-0.2, 1.7, -0.35] },
            { shape: 'box', dimensions: { width: 1.2, height: 0.45, depth: 0.9 }, color: SIEGE_WOOD, position: [0, 1.35, 0] },
            { shape: 'torus', dimensions: { diameter: 1.2, thickness: 0.08, tessellation: 16 }, color: GOLD, position: [0, 1.8, 0], emissive: 0.4 },
        ],
        [{ type: 'ambient', emitRate: 6, color1: [0.8, 0.7, 0.3, 0.5], color2: [0.6, 0.5, 0.2, 0.3], minSize: 0.05, maxSize: 0.12, minLifeTime: 0.3, maxLifeTime: 0.6, offsetY: 2.0 }]),
        upgradePaths: [],
        parentId: 'clockworkTower',
        projectileColor: [0.85, 0.80, 0.45],
    },

    // ===== TIER 5-8 — Rapid Fire Branch B: Siege Ballista line =====
    {
        id: 'siegeBallistaTower',
        name: 'Siege Ballista',
        description: 'Massive ballista bolts deal tremendous single-target damage.',
        tier: 5, tree: 'medieval', category: 'siege',
        stats: { damage: 50, range: 10, fireRate: 0.5, cost: 200 },
        ability: { name: 'Armor Piercing', type: 'passive', cooldown: 0, effect: { kind: 'armorShatter', reductionPerStack: 0.08, maxStacks: 5, duration: 5 }, description: 'Bolts shatter armor: -8% per stack (max 5)' },
        visual: medievalVisual(1.6, 1.8, DARK_STONE, [
            { shape: 'box', dimensions: { width: 2.0, height: 0.3, depth: 1.0 }, color: SIEGE_WOOD, position: [0, 1.0, 0] },
            { shape: 'cylinder', dimensions: { diameter: 0.15, height: 1.2, tessellation: 6 }, color: IRON, position: [0, 1.4, 0] },
            { shape: 'box', dimensions: { width: 0.4, height: 0.2, depth: 0.15 }, color: DARK_IRON, position: [0, 1.0, 0.35] },
        ]),
        upgradePaths: ['grandBallista'],
        parentId: 'scorpionTower',
        projectileColor: [0.4, 0.4, 0.45],
    },
    {
        id: 'grandBallista',
        name: 'Grand Ballista',
        description: 'An enormous ballista that can pierce through any armor.',
        tier: 6, tree: 'medieval', category: 'siege',
        stats: { damage: 70, range: 11, fireRate: 0.5, cost: 275 },
        ability: { name: 'Grand Piercing', type: 'passive', cooldown: 0, effect: { kind: 'armorShatter', reductionPerStack: 0.10, maxStacks: 6, duration: 6 }, description: '-10% armor per stack (max 6)' },
        visual: medievalVisual(1.8, 2.0, DARK_STONE, [
            { shape: 'box', dimensions: { width: 2.2, height: 0.35, depth: 1.2 }, color: SIEGE_WOOD, position: [0, 1.1, 0] },
            { shape: 'cylinder', dimensions: { diameter: 0.18, height: 1.4, tessellation: 6 }, color: IRON, position: [0, 1.6, 0] },
            { shape: 'box', dimensions: { width: 0.5, height: 0.25, depth: 0.2 }, color: DARK_IRON, position: [0, 1.1, 0.45] },
        ]),
        upgradePaths: ['titanBallista'],
        parentId: 'siegeBallistaTower',
        projectileColor: [0.4, 0.4, 0.4],
    },
    {
        id: 'titanBallista',
        name: 'Titan Ballista',
        description: 'A weapon of legend that can fell titans.',
        tier: 7, tree: 'medieval', category: 'siege',
        stats: { damage: 95, range: 12, fireRate: 0.5, cost: 375 },
        ability: { name: 'Titan Bolt', type: 'passive', cooldown: 0, effect: { kind: 'armorShatter', reductionPerStack: 0.12, maxStacks: 7, duration: 7 }, description: '-12% armor per stack (max 7)' },
        visual: medievalVisual(2.0, 2.2, DARK_STONE, [
            { shape: 'box', dimensions: { width: 2.4, height: 0.4, depth: 1.4 }, color: SIEGE_WOOD, position: [0, 1.2, 0] },
            { shape: 'cylinder', dimensions: { diameter: 0.2, height: 1.6, tessellation: 6 }, color: IRON, position: [0, 1.8, 0] },
            { shape: 'box', dimensions: { width: 0.6, height: 0.3, depth: 0.25 }, color: DARK_IRON, position: [0, 1.2, 0.5] },
        ]),
        upgradePaths: ['kingdomBreaker'],
        parentId: 'grandBallista',
        projectileColor: [0.35, 0.35, 0.4],
    },
    {
        id: 'kingdomBreaker',
        name: 'Kingdom Breaker',
        description: 'The ultimate siege weapon. No armor can withstand its bolts.',
        tier: 8, tree: 'medieval', category: 'siege',
        stats: { damage: 130, range: 13, fireRate: 0.5, cost: 500 },
        ability: { name: 'Kingdom Breaker', type: 'passive', cooldown: 0, effect: { kind: 'armorShatter', reductionPerStack: 0.15, maxStacks: 8, duration: 8 }, description: '-15% armor per stack (max 8). Devastating single hits.' },
        visual: medievalVisual(2.2, 2.4, [0.25, 0.25, 0.28], [
            { shape: 'box', dimensions: { width: 2.6, height: 0.45, depth: 1.6 }, color: SIEGE_WOOD, position: [0, 1.3, 0] },
            { shape: 'cylinder', dimensions: { diameter: 0.22, height: 1.8, tessellation: 6 }, color: [0.35, 0.35, 0.38], position: [0, 2.0, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.3, tessellation: 6 }, color: [0.9, 0.15, 0.10], position: [0, 2.9, 0], emissive: 0.5 },
            { shape: 'torus', dimensions: { diameter: 2.0, thickness: 0.08, tessellation: 16 }, color: GOLD, position: [0, 0.2, 0], emissive: 0.2 },
        ],
        [{ type: 'ambient', emitRate: 4, color1: [0.5, 0.4, 0.3, 0.4], color2: [0.3, 0.25, 0.2, 0.2], minSize: 0.08, maxSize: 0.18, minLifeTime: 0.5, maxLifeTime: 1.0, offsetY: 2.5 }]),
        upgradePaths: [],
        parentId: 'titanBallista',
        projectileColor: [0.9, 0.15, 0.10],
    },

    // ===== TIER 5-8 — Support Branch A: Commander line =====
    {
        id: 'commanderTower',
        name: 'Commander Tower',
        description: 'A commander inspires all nearby towers to fight harder.',
        tier: 5, tree: 'medieval', category: 'support',
        stats: { damage: 15, range: 5, fireRate: 0.9, cost: 200 },
        ability: { name: 'Inspire', type: 'passive', cooldown: 0, effect: { kind: 'auraBuff', bonusDamage: 6, bonusFireRate: 0.3, bonusRange: 1, radius: 7 }, description: '+6 damage, +0.3 fire rate, +1 range to nearby towers' },
        visual: medievalVisual(2.2, 1.7, STONE, [
            { shape: 'box', dimensions: { width: 1.8, height: 0.5, depth: 1.8 }, color: DARK_STONE, position: [0, 1.2, 0] },
            { shape: 'cone', dimensions: { diameter: 2.0, height: 1.2, tessellation: 4 }, color: [0.48, 0.26, 0.12], position: [0, 2.1, 0] },
            { shape: 'box', dimensions: { width: 0.1, height: 1.2, depth: 0.1 }, color: WOOD, position: [0, 2.3, 0] },
            { shape: 'box', dimensions: { width: 0.6, height: 0.07, depth: 0.3 }, color: GOLD, position: [0, 2.9, 0] },
        ]),
        upgradePaths: ['marshalTower'],
        parentId: 'warHall',
        projectileColor: [0.85, 0.70, 0.25],
    },
    {
        id: 'marshalTower',
        name: 'Marshal Tower',
        description: 'A marshal\'s presence turns towers into elite warriors.',
        tier: 6, tree: 'medieval', category: 'support',
        stats: { damage: 18, range: 6, fireRate: 1.0, cost: 275 },
        ability: { name: 'Marshal\'s Command', type: 'passive', cooldown: 0, effect: { kind: 'auraBuff', bonusDamage: 8, bonusFireRate: 0.4, bonusRange: 1.5, radius: 8 }, description: '+8 damage, +0.4 fire rate, +1.5 range to nearby towers' },
        visual: medievalVisual(2.5, 1.8, STONE, [
            { shape: 'box', dimensions: { width: 1.9, height: 0.55, depth: 1.9 }, color: DARK_STONE, position: [0, 1.35, 0] },
            { shape: 'cone', dimensions: { diameter: 2.2, height: 1.3, tessellation: 4 }, color: [0.45, 0.24, 0.10], position: [0, 2.3, 0] },
            { shape: 'box', dimensions: { width: 0.1, height: 1.4, depth: 0.1 }, color: GOLD, position: [0, 2.6, 0] },
            { shape: 'box', dimensions: { width: 0.7, height: 0.08, depth: 0.35 }, color: GOLD, position: [0, 3.3, 0] },
        ]),
        upgradePaths: ['highMarshalTower'],
        parentId: 'commanderTower',
        projectileColor: [0.85, 0.75, 0.30],
    },
    {
        id: 'highMarshalTower',
        name: 'High Marshal Tower',
        description: 'A legendary commander whose aura spans the battlefield.',
        tier: 7, tree: 'medieval', category: 'support',
        stats: { damage: 22, range: 6, fireRate: 1.0, cost: 375 },
        ability: { name: 'High Command', type: 'passive', cooldown: 0, effect: { kind: 'auraBuff', bonusDamage: 10, bonusFireRate: 0.5, bonusRange: 2, radius: 9 }, description: '+10 damage, +0.5 fire rate, +2 range to nearby towers' },
        visual: medievalVisual(2.8, 1.9, STONE, [
            { shape: 'box', dimensions: { width: 2.0, height: 0.6, depth: 2.0 }, color: DARK_STONE, position: [0, 1.5, 0] },
            { shape: 'cone', dimensions: { diameter: 2.3, height: 1.4, tessellation: 4 }, color: GOLD, position: [0, 2.5, 0] },
            { shape: 'box', dimensions: { width: 0.12, height: 1.6, depth: 0.12 }, color: GOLD, position: [0, 2.9, 0] },
            { shape: 'box', dimensions: { width: 0.8, height: 0.1, depth: 0.4 }, color: GOLD, position: [0, 3.7, 0] },
        ]),
        upgradePaths: ['grandMarshalCitadel'],
        parentId: 'marshalTower',
        projectileColor: [0.90, 0.80, 0.35],
    },
    {
        id: 'grandMarshalCitadel',
        name: 'Grand Marshal Citadel',
        description: 'The ultimate support structure. Massively buffs all towers in range.',
        tier: 8, tree: 'medieval', category: 'support',
        stats: { damage: 25, range: 7, fireRate: 1.0, cost: 500 },
        ability: { name: 'Grand Marshal\'s Aura', type: 'passive', cooldown: 0, effect: { kind: 'auraBuff', bonusDamage: 15, bonusFireRate: 0.6, bonusRange: 2.5, radius: 10 }, description: '+15 damage, +0.6 fire rate, +2.5 range to all towers in huge radius' },
        visual: medievalVisual(3.2, 2.0, [0.80, 0.75, 0.65], [
            { shape: 'box', dimensions: { width: 2.2, height: 0.7, depth: 2.2 }, color: DARK_STONE, position: [0, 1.7, 0] },
            { shape: 'cone', dimensions: { diameter: 2.5, height: 1.6, tessellation: 4 }, color: GOLD, position: [0, 2.9, 0] },
            { shape: 'box', dimensions: { width: 0.14, height: 2.0, depth: 0.14 }, color: GOLD, position: [0, 3.3, 0] },
            { shape: 'box', dimensions: { width: 1.0, height: 0.12, depth: 0.5 }, color: GOLD, position: [0, 4.3, 0] },
            { shape: 'torus', dimensions: { diameter: 2.0, thickness: 0.08, tessellation: 16 }, color: GOLD, position: [0, 1.0, 0], emissive: 0.4 },
        ],
        [{ type: 'ambient', emitRate: 8, color1: [0.9, 0.8, 0.3, 0.5], color2: [0.8, 0.7, 0.2, 0.3], minSize: 0.08, maxSize: 0.18, minLifeTime: 0.5, maxLifeTime: 1.2, offsetY: 3.0 }]),
        upgradePaths: [],
        parentId: 'highMarshalTower',
        projectileColor: [0.95, 0.85, 0.40],
    },

    // ===== TIER 5-8 — Support Branch B: Warden (Trap/Slow) line =====
    {
        id: 'wardenTower',
        name: 'Warden Tower',
        description: 'Traps enemies in a snaring field that slows movement.',
        tier: 5, tree: 'medieval', category: 'control',
        stats: { damage: 12, range: 6, fireRate: 1.0, cost: 200 },
        ability: { name: 'Snare Trap', type: 'active_auto', cooldown: 3, effect: { kind: 'trapField', trapType: 'snare', radius: 3, duration: 2, dps: 3, slow: 0.4 }, description: 'Every 3s, creates a snare field that slows and damages' },
        visual: medievalVisual(1.8, 1.5, DARK_STONE, [
            { shape: 'box', dimensions: { width: 1.6, height: 0.4, depth: 1.6 }, color: IRON, position: [0, 1.0, 0] },
            { shape: 'cylinder', dimensions: { diameter: 0.8, height: 0.8, tessellation: 8 }, color: DARK_STONE, position: [0, 1.4, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.3, tessellation: 6 }, color: [0.5, 0.3, 0.8], position: [0, 1.9, 0], emissive: 0.4 },
        ]),
        upgradePaths: ['dungeonTower'],
        parentId: 'warHall',
        projectileColor: [0.5, 0.3, 0.8],
        statusEffect: { effect: StatusEffect.SLOWED, duration: 1.5, strength: 0.3, chance: 0.5 },
    },
    {
        id: 'dungeonTower',
        name: 'Dungeon Tower',
        description: 'Dark dungeon magic traps enemies in a web of pain.',
        tier: 6, tree: 'medieval', category: 'control',
        stats: { damage: 16, range: 6, fireRate: 1.0, cost: 275 },
        ability: { name: 'Dungeon Snare', type: 'active_auto', cooldown: 3, effect: { kind: 'trapField', trapType: 'snare', radius: 3.5, duration: 2.5, dps: 5, slow: 0.5 }, description: 'Every 3s, stronger snare field' },
        visual: medievalVisual(2.0, 1.5, [0.25, 0.22, 0.28], [
            { shape: 'box', dimensions: { width: 1.6, height: 0.45, depth: 1.6 }, color: DARK_IRON, position: [0, 1.1, 0] },
            { shape: 'cylinder', dimensions: { diameter: 0.9, height: 1.0, tessellation: 8 }, color: [0.20, 0.18, 0.22], position: [0, 1.6, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.35, tessellation: 6 }, color: [0.6, 0.2, 0.8], position: [0, 2.2, 0], emissive: 0.5 },
        ]),
        upgradePaths: ['oublietteTower'],
        parentId: 'wardenTower',
        projectileColor: [0.6, 0.2, 0.8],
        statusEffect: { effect: StatusEffect.SLOWED, duration: 2, strength: 0.4, chance: 0.6 },
    },
    {
        id: 'oublietteTower',
        name: 'Oubliette Tower',
        description: 'Enemies are trapped in a nightmare from which few escape.',
        tier: 7, tree: 'medieval', category: 'control',
        stats: { damage: 20, range: 7, fireRate: 1.0, cost: 375 },
        ability: { name: 'Oubliette', type: 'active_auto', cooldown: 3, effect: { kind: 'trapField', trapType: 'prison', radius: 4, duration: 3, dps: 8, slow: 0.6 }, description: 'Every 3s, prison trap with heavy slow and damage' },
        visual: medievalVisual(2.4, 1.6, [0.20, 0.18, 0.22], [
            { shape: 'box', dimensions: { width: 1.7, height: 0.5, depth: 1.7 }, color: DARK_IRON, position: [0, 1.3, 0] },
            { shape: 'cylinder', dimensions: { diameter: 1.0, height: 1.2, tessellation: 8 }, color: [0.18, 0.15, 0.20], position: [0, 1.9, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.4, tessellation: 6 }, color: [0.7, 0.15, 0.85], position: [0, 2.6, 0], emissive: 0.6 },
        ]),
        upgradePaths: ['blackTower'],
        parentId: 'dungeonTower',
        projectileColor: [0.7, 0.15, 0.85],
        statusEffect: { effect: StatusEffect.SLOWED, duration: 2.5, strength: 0.5, chance: 0.7 },
    },
    {
        id: 'blackTower',
        name: 'Black Tower',
        description: 'The ultimate prison. Enemies that enter its domain never leave.',
        tier: 8, tree: 'medieval', category: 'control',
        stats: { damage: 25, range: 7, fireRate: 1.0, cost: 500 },
        ability: { name: 'Black Prison', type: 'active_auto', cooldown: 2.5, effect: { kind: 'trapField', trapType: 'prison', radius: 5, duration: 3.5, dps: 12, slow: 0.7 }, description: 'Every 2.5s, massive prison field. Near-complete slow.' },
        visual: medievalVisual(2.8, 1.7, [0.15, 0.12, 0.18], [
            { shape: 'box', dimensions: { width: 1.8, height: 0.55, depth: 1.8 }, color: DARK_IRON, position: [0, 1.5, 0] },
            { shape: 'cylinder', dimensions: { diameter: 1.1, height: 1.4, tessellation: 8 }, color: [0.12, 0.10, 0.15], position: [0, 2.2, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.5, tessellation: 8 }, color: [0.8, 0.1, 0.9], position: [0, 3.0, 0], emissive: 0.7 },
            { shape: 'torus', dimensions: { diameter: 1.8, thickness: 0.06, tessellation: 16 }, color: [0.6, 0.1, 0.8], position: [0, 0.5, 0], emissive: 0.3 },
        ],
        [{ type: 'shadow', emitRate: 6, color1: [0.5, 0.1, 0.7, 0.5], color2: [0.3, 0.05, 0.5, 0.3], minSize: 0.1, maxSize: 0.25, minLifeTime: 0.5, maxLifeTime: 1.0, offsetY: 2.5 }]),
        upgradePaths: [],
        parentId: 'oublietteTower',
        projectileColor: [0.8, 0.1, 0.9],
        statusEffect: { effect: StatusEffect.STUNNED, duration: 0.5, strength: 1.0, chance: 0.3 },
    },

    // ===== TIER 5-8 — Defense Branch A: Catapult/Trebuchet line =====
    {
        id: 'catapultTower',
        name: 'Catapult Tower',
        description: 'Hurls boulders with devastating splash damage.',
        tier: 5, tree: 'medieval', category: 'siege',
        stats: { damage: 55, range: 9, fireRate: 0.4, cost: 200 },
        ability: { name: 'Boulder Smash', type: 'passive', cooldown: 0, effect: { kind: 'siegeShot', bonusDamage: 20, splashRadius: 3 }, description: '+20 bonus damage with 3 radius splash' },
        visual: medievalVisual(1.8, 2.0, DARK_STONE, [
            { shape: 'box', dimensions: { width: 1.5, height: 0.6, depth: 0.6 }, color: SIEGE_WOOD, position: [0, 1.2, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.4, tessellation: 6 }, color: STONE, position: [0, 1.6, 0] },
        ]),
        upgradePaths: ['trebuchetFortress'],
        parentId: 'rampartTower',
        projectileColor: [0.6, 0.5, 0.4],
    },
    {
        id: 'trebuchetFortress',
        name: 'Trebuchet Fortress',
        description: 'A mighty trebuchet that launches devastating payloads.',
        tier: 6, tree: 'medieval', category: 'siege',
        stats: { damage: 75, range: 10, fireRate: 0.4, cost: 275 },
        ability: { name: 'Fire Boulder', type: 'passive', cooldown: 0, effect: { kind: 'siegeShot', bonusDamage: 30, splashRadius: 3.5 }, description: '+30 bonus damage with 3.5 radius splash' },
        visual: medievalVisual(2.0, 2.2, DARK_STONE, [
            { shape: 'box', dimensions: { width: 1.8, height: 0.7, depth: 0.7 }, color: SIEGE_WOOD, position: [0, 1.3, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.5, tessellation: 6 }, color: [0.9, 0.4, 0.1], position: [0, 1.8, 0], emissive: 0.3 },
        ]),
        upgradePaths: ['warTrebuchet'],
        parentId: 'catapultTower',
        projectileColor: [0.9, 0.4, 0.1],
    },
    {
        id: 'warTrebuchet',
        name: 'War Trebuchet',
        description: 'Wartime engineering at its finest. Massive area devastation.',
        tier: 7, tree: 'medieval', category: 'siege',
        stats: { damage: 100, range: 11, fireRate: 0.4, cost: 375 },
        ability: { name: 'War Payload', type: 'passive', cooldown: 0, effect: { kind: 'siegeShot', bonusDamage: 40, splashRadius: 4 }, description: '+40 bonus damage with 4 radius splash' },
        visual: medievalVisual(2.2, 2.4, DARK_STONE, [
            { shape: 'box', dimensions: { width: 2.0, height: 0.8, depth: 0.8 }, color: SIEGE_WOOD, position: [0, 1.5, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.6, tessellation: 6 }, color: [1.0, 0.35, 0.0], position: [0, 2.0, 0], emissive: 0.4 },
        ]),
        upgradePaths: ['doomTrebuchet'],
        parentId: 'trebuchetFortress',
        projectileColor: [1.0, 0.35, 0.0],
    },
    {
        id: 'doomTrebuchet',
        name: 'Doom Trebuchet',
        description: 'The ultimate siege weapon. Burning boulders obliterate everything.',
        tier: 8, tree: 'medieval', category: 'siege',
        stats: { damage: 140, range: 12, fireRate: 0.4, cost: 500 },
        ability: { name: 'Doom Boulder', type: 'passive', cooldown: 0, effect: { kind: 'siegeShot', bonusDamage: 60, splashRadius: 4.5 }, description: '+60 bonus damage with 4.5 radius massive splash' },
        visual: medievalVisual(2.4, 2.6, [0.22, 0.22, 0.25], [
            { shape: 'box', dimensions: { width: 2.2, height: 0.9, depth: 0.9 }, color: SIEGE_WOOD, position: [0, 1.6, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.7, tessellation: 8 }, color: [1.0, 0.30, 0.0], position: [0, 2.2, 0], emissive: 0.6 },
            { shape: 'torus', dimensions: { diameter: 2.2, thickness: 0.08, tessellation: 16 }, color: [0.9, 0.3, 0.0], position: [0, 0.3, 0], emissive: 0.3 },
        ],
        [{ type: 'fire', emitRate: 10, color1: [1, 0.5, 0.1, 0.6], color2: [1, 0.3, 0, 0.4], minSize: 0.1, maxSize: 0.25, minLifeTime: 0.3, maxLifeTime: 0.7, offsetY: 2.0 }]),
        upgradePaths: [],
        parentId: 'warTrebuchet',
        projectileColor: [1.0, 0.30, 0.0],
    },

    // ===== TIER 5-8 — Defense Branch B: Saboteur/Engineer line =====
    {
        id: 'saboteurTower',
        name: 'Saboteur Tower',
        description: 'Weakens enemies with debilitating traps and sabotage.',
        tier: 5, tree: 'medieval', category: 'debuff',
        stats: { damage: 20, range: 7, fireRate: 0.8, cost: 200 },
        ability: { name: 'Sabotage', type: 'passive', cooldown: 0, effect: { kind: 'armorShatter', reductionPerStack: 0.10, maxStacks: 6, duration: 5 }, description: '-10% enemy defense per stack (max 6)' },
        visual: medievalVisual(1.6, 1.6, IRON, [
            { shape: 'box', dimensions: { width: 1.0, height: 0.5, depth: 1.0 }, color: DARK_IRON, position: [0, 1.0, 0] },
            { shape: 'cylinder', dimensions: { diameter: 0.4, height: 0.6, tessellation: 6 }, color: [0.6, 0.5, 0.3], position: [0, 1.4, 0] },
        ]),
        upgradePaths: ['engineerTower'],
        parentId: 'rampartTower',
        projectileColor: [0.5, 0.5, 0.3],
    },
    {
        id: 'engineerTower',
        name: 'Engineer Tower',
        description: 'Master engineer with mechanical traps and gadgets.',
        tier: 6, tree: 'medieval', category: 'debuff',
        stats: { damage: 25, range: 7, fireRate: 0.9, cost: 275 },
        ability: { name: 'Engineer\'s Gadgets', type: 'passive', cooldown: 0, effect: { kind: 'armorShatter', reductionPerStack: 0.12, maxStacks: 7, duration: 6 }, description: '-12% enemy defense per stack (max 7)' },
        visual: medievalVisual(1.8, 1.7, IRON, [
            { shape: 'box', dimensions: { width: 1.2, height: 0.55, depth: 1.2 }, color: DARK_IRON, position: [0, 1.1, 0] },
            { shape: 'cylinder', dimensions: { diameter: 0.45, height: 0.7, tessellation: 6 }, color: GOLD, position: [0, 1.5, 0] },
        ]),
        upgradePaths: ['siegeEngineerTower'],
        parentId: 'saboteurTower',
        projectileColor: [0.65, 0.55, 0.3],
    },
    {
        id: 'siegeEngineerTower',
        name: 'Siege Engineer',
        description: 'Grand engineer whose devices weaken entire enemy formations.',
        tier: 7, tree: 'medieval', category: 'debuff',
        stats: { damage: 32, range: 8, fireRate: 1.0, cost: 375 },
        ability: { name: 'Siege Engineering', type: 'passive', cooldown: 0, effect: { kind: 'armorShatter', reductionPerStack: 0.14, maxStacks: 8, duration: 7 }, description: '-14% enemy defense per stack (max 8)' },
        visual: medievalVisual(2.0, 1.8, IRON, [
            { shape: 'box', dimensions: { width: 1.4, height: 0.6, depth: 1.4 }, color: DARK_IRON, position: [0, 1.2, 0] },
            { shape: 'cylinder', dimensions: { diameter: 0.5, height: 0.8, tessellation: 6 }, color: GOLD, position: [0, 1.7, 0] },
            { shape: 'torus', dimensions: { diameter: 0.8, thickness: 0.05, tessellation: 12 }, color: GOLD, position: [0, 1.3, 0], emissive: 0.2 },
        ]),
        upgradePaths: ['grandArchitect'],
        parentId: 'engineerTower',
        projectileColor: [0.75, 0.65, 0.35],
    },
    {
        id: 'grandArchitect',
        name: 'Grand Architect',
        description: 'The ultimate debuffer. Renders enemies completely vulnerable.',
        tier: 8, tree: 'medieval', category: 'debuff',
        stats: { damage: 40, range: 8, fireRate: 1.0, cost: 500 },
        ability: { name: 'Grand Design', type: 'passive', cooldown: 0, effect: { kind: 'armorShatter', reductionPerStack: 0.18, maxStacks: 10, duration: 8 }, description: '-18% enemy defense per stack (max 10). Complete vulnerability.' },
        visual: medievalVisual(2.4, 2.0, [0.50, 0.48, 0.52], [
            { shape: 'box', dimensions: { width: 1.6, height: 0.65, depth: 1.6 }, color: DARK_IRON, position: [0, 1.4, 0] },
            { shape: 'cylinder', dimensions: { diameter: 0.6, height: 1.0, tessellation: 8 }, color: GOLD, position: [0, 2.0, 0] },
            { shape: 'sphere', dimensions: { diameter: 0.35, tessellation: 6 }, color: GOLD, position: [0, 2.6, 0], emissive: 0.5 },
            { shape: 'torus', dimensions: { diameter: 1.4, thickness: 0.06, tessellation: 16 }, color: GOLD, position: [0, 0.5, 0], emissive: 0.3 },
        ],
        [{ type: 'ambient', emitRate: 6, color1: [0.9, 0.8, 0.3, 0.4], color2: [0.7, 0.6, 0.2, 0.3], minSize: 0.06, maxSize: 0.15, minLifeTime: 0.4, maxLifeTime: 0.9, offsetY: 2.2 }]),
        upgradePaths: [],
        parentId: 'siegeEngineerTower',
        projectileColor: [0.90, 0.80, 0.40],
    },
];
